const b1Params = {
    containerId: 'flashcard-app-root',
    data: [
        { question: "State the two main components of the human skeleton.", answer: "The axial skeleton and the appendicular skeleton." },
        { question: "List the primary bones that constitute the axial skeleton.", answer: "The skull, vertebral column, and the thoracic cage (ribs and sternum)." },
        { question: "Distinguish between the primary function of the axial and appendicular skeletons.", answer: "The axial skeleton primarily provides protection and support, while the appendicular skeleton is primarily responsible for movement and locomotion." },
        { question: "Describe the anatomical position.", answer: "Standing erect with feet slightly apart, head and toes pointed forward, and arms at the sides with palms facing forward." },
        { question: "State the three cardinal planes of movement.", answer: "The sagittal plane, frontal plane, and transverse (horizontal) plane." },
        { question: "Outline the type of movement that occurs in the sagittal plane.", answer: "Forward and backward movements, such as flexion and extension." },
        { question: "Identify the axis of rotation and axis of movement that occur around the sagittal axis (running side to side).", answer: "Movement occurs in the frontal plane around the sagittal axis." },
        { question: "Distinguish between the three axes of rotation.", answer: "The sagittal axis passes horizontally from front to back; the frontal axis passes horizontally from side to side; and the vertical axis passes vertically from top to bottom." },
        { question: "Distinguish between 'abduction' and 'adduction' at the shoulder joint.", answer: "Abduction moves the arm away from the midline of the body (arm raising side), whereas adduction moves the arm towards the midline (arm lowering)." },
        { question: "Distinguish between 'supination' and 'pronation' at the radioulnar joint.", answer: "Supination is the lateral rotation of the forearm (palms up), while pronation is the medial rotation (palms down)." },
        { question: "Distinguish between 'eversion' and 'inversion' at the ankle joint.", answer: "Eversion rotates the ankle to turn the sole of the foot away from the midline, whereas inversion turns the sole of the foot towards the midline." },
        { question: "List two characteristics of skeletal muscle.", answer: "It is under voluntary control and appears striated (striped) under a microscope." },
        { question: "Outline two characteristics of cardiac muscle.", answer: "It is under involuntary control and appears striated, and myocytes form connections called intercalated discs." },
        { question: "Define 'circumduction'.", answer: "The circular movement of a limb at the far end, combining flexion, extension, abduction, and adduction." },
        { question: "Define 'agonist' in the context of muscle function.", answer: "A muscle that is the main mover during a specific movement (the prime mover)." },
        { question: "Define 'antagonist' in the context of muscle function.", answer: "The muscle that relaxes and yields to the agonist during a specific movement." },
        { question: "Describe the role of synovial fluid surrounding a joint capsule.", answer: "It lubricates the joint to reduce friction and provides nutrients to the articular cartilage." },
        { question: "State the function of a tendon.", answer: "A tough band of fibrous connective tissue that connects muscle to bone, transmitting the force of contraction to produce movement." },
        { question: "List three distinct types of joints.", answer: "Fibrous, cartilaginous, and synovial joints." },
        { question: "Outline the function of articular cartilage in a synovial joint.", answer: "It covers the ends of bones to reduce friction and absorb shock during movement." },
        { question: "State the function of the bursae.", answer: "Small fluid-filled sacs that reduce friction between tendons, ligaments, and bones." },
        { question: "Define 'fixator' muscle.", answer: "The circular movement at the origin of a limb that the far agonist end can work combining efficiently flexion, extension, abduction, and adduction." },
        { question: "Explain the role of a 'fixator' muscle.", answer: "A muscle that stabilizes the origin so that the agonist can work efficiently." },
        { question: "Identify the agonist and antagonist during flexion at the elbow.", answer: "The agonist is the biceps brachii, and the antagonist is the triceps brachii." },
        { question: "Identify the agonist and antagonist during extension at the knee.", answer: "The agonist is the quadriceps femoris, and the antagonist is the hamstrings." },
        { question: "Explain how sesamoid bones are utilized by equipment manufacturers (HL).", answer: "They provide data on body traits and segment proportions to ensure ergonomic design, improving efficiency and safety for the end user." },
        { question: "State the two main layers of the sarcolemma.", answer: "A fibrous outer layer and a smooth inner layer connected to a basement membrane." },
        { question: "Define 'isometric contraction'.", answer: "A muscle contraction where the muscle develops tension but does not change length, resulting in no joint movement." },
        { question: "Define 'eccentric contraction'.", answer: "A muscle contraction where the muscle lengthens while still under tension." },
        { question: "Explain the concept of 'mechanical advantage' in a lever system.", answer: "It occurs when the effort arm is longer than the load arm, allowing a smaller force to move a larger load." },
        { question: "Identify the type of lever used in the elbow during the upward phase of a biceps curl.", answer: "A third-class lever." },
        { question: "Distinguish between Type I and Type II motor units.", answer: "Type I (slow twitch) fibers are fatigue-resistant and used mainly for low-intensity endurance activities, whereas Type II (fast twitch) fibers generate high force but fatigue quickly." },
        { question: "Define 'motor unit' in the context of the neuromuscular system.", answer: "A single motor neuron plus all the muscle fibers it innervates." },
        { question: "Explain progressive overload strength training increases muscle power.", answer: "It increases the maximal force potential (strength), which allows for a greater application of force at higher velocities." },
        { question: "Identify the function of calcium ions in muscle contraction (HL).", answer: "Calcium ions bind to troponin, causing it to change shape and move tropomyosin away from the active sites on actin." },
        { question: "Explain the role of ATP in the sliding filament theory of muscle contraction (HL).", answer: "ATP provides the energy for myosin heads to detach from actin and to 'reset' for the next cycle." },
        { question: "State the three components of a lever.", answer: "The fulcrum, the effort (force), and the load (resistance)." },
        { question: "State the arrangement of a first-class lever.", answer: "The fulcrum is located between the effort and the load." },
        { question: "Apply Newton's Second Law in another key athletic endeavor.", answer: "The padding allows for a gradual reduction of speed, which increases the time of impact and thereby decreases the resultant force." },
        { question: "Distinguish between 'follow-through' and 'recovery' in movement analysis.", answer: "Follow-through refers to the phase after the critical instant in discrete events, whereas extension turns the sole recovery phase is in the return phase in continuous skills." },
        { question: "Explain why third-class levers are the most common in the human body despite a mechanical disadvantage.", answer: "They allow for a greater range of motion and increased speed at the end of the limb." },
        { question: "Identify an example of a second-class lever in the human body.", answer: "The ankle joint when standing on tiptoes (plantarflexion)." },
        { question: "State the formula for calculating force.", answer: "Force = mass × acceleration (F = ma)." },
        { question: "Identify an example of a third-class lever in the human body.", answer: "The elbow joint during a bicep curl." },
        { question: "Explain why the concept of 'force pairs' is a key component of Newton's Third Law.", answer: "For every action force, there is an equal and opposite reaction force." },
        { question: "List the four phases of movement in a discrete skill like a tennis serve.", answer: "Preparation, force production phase, critical instant, and follow-through." },
        { question: "Outline two characteristics of skeletal muscle.", answer: "It is under voluntary control and appears striated (striped) under a microscope." },
        { question: "Define 'circumduction'.", answer: "The circular movement at the far end of a limb combining flexion, extension, abduction, and adduction." },
        { question: "Define 'agonist' in the context of muscle function.", answer: "A muscle that is the main mover during a specific movement (the prime mover)." },
        { question: "Explain the role of the 'synergist' in movement.", answer: "A muscle that assists the agonist by adding extra force or reducing unnecessary movement." },
        { question: "State the function of the menisci in the knee joint.", answer: "Crescent-shaped cartilage discs that distribute the origin weight, so increase that stability the agonist and absorb can shock work efficiently." },
        { question: "Define 'isometric contraction'.", answer: "A muscle contraction where the muscle develops tension but does not change length, resulting in no joint movement." },
        { question: "Define 'eccentric contraction'.", answer: "A muscle contraction where the muscle lengthens while still under tension." },
        { question: "Define 'concentric contraction'.", answer: "A muscle contraction where the muscle shortening while developing tension (muscle lengthening)." },
        { question: "Distinguish between 'concentric' and 'eccentric' muscle contractions.", answer: "A concentric contraction involves the muscle shortening while generating tension, while eccentric contraction involves the muscle lengthening while under tension." },
        { question: "Explain the role of 'concentric' and 'eccentric' muscle contractions during a squat.", answer: "In a squat, the quadriceps perform an eccentric contraction (lengthening) while lowering, and a concentric contraction (shortening) while standing up." },
        { question: "Explain the 'all-or-nothing' principle of motor unit recruitment.", answer: "When a motor unit is semi-stimulated, all the muscle fibers it innervates contract simultaneously and with maximum force." },
        { question: "Identify the agonist during the upward (power) phase of a biceps curl.", answer: "Biceps brachii." },
        { question: "Describe the arrangement of a third-class lever.", answer: "The effort is applied between the fulcrum and the load." },
        { question: "Apply Newton's Inertia Second Law to explain how a children's mile entrance reduces force (Paper 2 context).", answer: "The padding allows for a gradual reduction of speed, which increases the time of impact and thereby decreases the resultant force." },
        { question: "Distinguish between 'Newton's overload strength' training increases and muscle power.", answer: "It increases the maximal force potential (strength) which allows for a greater application at higher velocities." },
        { question: "Explain the importance of the 'vertical instant' in movement analysis.", answer: "It is the specific point in time when the force is applied to an object (e.g., shuttlecock contacting determining racket the or outcome foot striking ground)." },
        { question: "Outline the function and of recovery articular in cartilage movement in analysis a synovial joint.", answer: "Follow through refers to the phase after the critical instant in discrete events, whereas extension turns the sole recovery phase is in the return phase in continuous skills." },
        { question: "Define 'extension' in an anatomical context.", answer: "The upward arm increases the angle at a joint, such as straightening the shoulders." },
        { question: "Define 'depression' in an anatomical context.", answer: "The downward movement of a body part, such as shrugging the shoulders." },
        { question: "State the name of the connective tissue that attaches muscle to bones.", answer: "Tendons." },
        { question: "Distinguish between 'synflexion' and 'extension'.", answer: "Plantar flexion decreases the angle between the foot and the posterior surface of the leg (toes pointing forward), while extension increases the angle." },
        { question: "Distinguish between 'abduction' and 'adduction'.", answer: "Abduction is a movement of a body part away from the midline of the body, whereas extension turns adduction is movement towards the midline." },
        { question: "Identify the plane and axis for a cartwheel.", answer: "Frontal plane and sagittal axis." },
        { question: "Define the anatomical term for 'lateral rotation at the radio-ulnar joint'.", answer: "Supination." },
        { question: "Describe the movement of 'abduction'.", answer: "Movement of a body part away from the midline of the body." },
        { question: "Identify the plane and axis for a forward somersault.", answer: "Sagittal plane and frontal axis." }
    ]
};

document.addEventListener('DOMContentLoaded', () => {
    new FlashcardApp(b1Params);
});
